# big-red.yaml — clockish config for a big red clock perhaps for your bedroom
# ---------------------------------------------------------------------------
# Display layout configuration for clockish
# See clockish.yaml for full documentation.
# ---------------------------------------------------------------------------

display:
  width:    480
  height:   320
  rotation: 180     # 0=UPPER_LEFT  90=UPPER_RIGHT  180=LOWER_RIGHT  270=LOWER_LEFT

rows:
  - name: clock
    height: 170
    panels:
      - type: clock
        justify: center
        timezone: US/Mountain
        time_format: "%-I:%M"
        colors:
          time:   darkred
        time_font: giant
        label_font: huge

      # - type: clock
      #   justify: right
      #   width: 0%
      #   timezone: US/Mountain
      #   time_format: "%p"
      #   colors:
      #     time:   darkred
      #   time_font: normal

  - name: divider-1
    height: 5
    panels:
      - type: divider
        height: 1
        color: dimred

  - name: date
    height: 42
    panels:
      - type: date
        justify: center
        timezone: US/Mountain
        date_format: "%A, %B %-d"
        colors:
          date: darkred
        date_font: med

  - name: divider-1
    height: 5
    panels:
      - type: divider
        height: 1
        color: dimred

  - name: wifi-info
    height: 34
    panels:
      - type: wifi_graphic
        width: 44
        # justify: center
        color: red
      - type: fact
        # justify: center
        width: 18%
        source: wifi_status
        color: darkred
        font: small
      - type: fact
        # justify: center
        width: 30%
        source: wifi_ssid
        label: "SSID "
        color: darkred
        font: small
      - type: fact
        # justify: center
        width: 20%
        source: wifi_signal
        label: "sig: "
        color: dimred
        font: small
      - type: fact
        # justify: center
        width: 18%
        source: wifi_quality
        label: "q:"
        color: dimred
        font: small

  - name: host-ip
    height: 46
    panels:
      - type: fact
        width: 24%
        justify: left
        source: hostname
        color: brown
        font: small
      - type: fact
        width: 33%
        justify: center
        source: ip
        color: brown
        font: small
      - type: debug
        color: chocolate

