---
# big-red.yaml  --  clockish config for a big red clock perhaps for your bedroom
# ---------------------------------------------------------------------------
# Display layout configuration for clockish
# Display settings are in display.yaml  --  use configs/display/ili9486-landscape.yaml.
# ---------------------------------------------------------------------------

orientation: landscape

rows:
  - name: clock
    height: 170
    panels:
      - type: clock
        justify: center
        timezone: US/Mountain
        time_format: "%-I:%M"
        color: red
        font_size: giant

      - type: clock
        justify: center
        width: 10%
        timezone: US/Mountain
        time_format: "%p"
        color: darkred
        font_size: normal

  - name: divider-1
    height: 5
    panels:
      - type: divider
        height: 1
        color: dimred

  - name: date
    height: 42
    panels:
      - type: date
        justify: center
        timezone: US/Mountain
        date_format: "%A, %B %-d"
        color: darkred
        font_size: med

  - name: divider-1
    height: 5
    panels:
      - type: divider
        height: 1
        color: dimred

  - name: wifi-info
    height: 34
    panels:
      - type: wifi_graphic
        width: 44
        # justify: center
        color: red
      - type: fact
        # justify: center
        width: 18%
        source: wifi_status
        color: darkred
        font_size: small
      - type: fact
        # justify: center
        width: 30%
        source: wifi_ssid
        label: "SSID "
        color: darkred
        font_size: small
      - type: fact
        # justify: center
        width: 20%
        source: wifi_signal
        label: "sig: "
        color: dimred
        font_size: small
      - type: fact
        # justify: center
        width: 18%
        source: wifi_quality
        label: "q:"
        color: dimred
        font_size: small

  - name: host-ip
    height: 46
    panels:
      - type: fact
        width: 24%
        justify: left
        source: hostname
        color: brown
        font_size: small
      - type: fact
        width: 33%
        justify: center
        source: ip
        color: brown
        font_size: small
      - type: debug
        color: chocolate
