---
# clockish.yaml - config
# ---------------------------------------------------------------------------
# System information display: local time + all available fact sources.
# Display settings are in display.yaml  --  see configs/display/ for profiles.
# ---------------------------------------------------------------------------

orientation: portrait

rows:
  - name: app-header
    height: 40
    background: navy
    panels:
      - type: text
        # justify: center
        label: "clockish.py"
        color: silver
        font_size: normal

  - name: app-version
    height: 30
    background: navy
    panels:
      - type: fact
        # justify: center
        source: version
        label: "default"
        color: grey
        font_size: small

  - name: divider-1
    height: 5
    background: black
    panels:
      - type: divider
        height: 1
        color: darkgrey

  - name: local-clock
    height: 56
    panels:
      - type: clock
        # justify: center
        timezone: local
        time_format: 24hs
        color: white
        font_size: big

  - name: local-date
    height: 36
    panels:
      - type: date
        # justify: center
        timezone: local
        date_format: "%a, %B %-d %Y"
        color: pink
        font_size: normal

  - name: blank-1
    height: 6
    background: black
    panels:
      - type: blank

  - name: help1
    height: 40
    background: orange
    panels:
      - type: text
        # justify: center
        label: "check the docs"
        color: black
        font_size: normal

  - name: help2
    height: 40
    background: orange
    panels:
      - type: text
        # justify: center
        label: "to configure!"
        color: black
        font_size: normal

  - name: blank-2
    height: 6
    background: black
    panels:
      - type: blank

  - name: network
    height: 28
    background: darkgrey
    panels:
      - type: fact
        # justify: center
        source: hostname
        label: "default"
        color: yellow
        font_size: small
      - type: fact
        # justify: center
        source: ip
        # label: "default"
        color: cyan
        font_size: small

  - name: blank-3
    height: 6
    background: black
    panels:
      - type: blank

  - name: wifi-status
    height: 44
    background: darkred
    panels:
      - type: wifi_graphic
        width: 44
        # justify: center
        color: lime
        background: black
      - type: fact
        # justify: center
        source: wifi_status
        color: lime
        font_size: normal
      - type: fact
        # justify: center
        source: wifi_ssid
        label: "default"
        color: darklime
        font_size: normal

# - name: wifi-signal
#   height: 26
#   panels:
#     - type: fact
#       # justify: center
#       source: wifi_signal
#       label: "default"
#       color: yellow
#       font_size: small
#     - type: fact
#       # justify: center
#       source: wifi_quality
#       label: "default"
#       color: darkyellow
#       font_size: small

  - name: blank-4
    height: 6
    background: black
    panels:
      - type: blank

# - name: ntp
#   height: 26
#   panels:
#     - type: fact
#       # justify: center
#       source: ntp_status
#       label: "default"
#       color: cyan
#       font_size: small
#     - type: fact
#       # justify: center
#       source: ntp_upstream
#       label: "default"
#       color: steelblue
#       font_size: small

# - name: divider-3
#   height: 3
#   panels:
#     - type: divider
#       height: 1
#       color: darkgrey

  - name: cpu
    height: 26
    panels:
      - type: fact
        # justify: center
        source: cpu
        label: "default"
        color: yellow
        font_size: small
      - type: fact
        # justify: center
        source: cpu_load
        label: "default"
        color: darkyellow
        font_size: small

# - name: memory
#   height: 26
#   panels:
#     - type: fact
#       # justify: center
#       source: mem
#       label: "default"
#       color: purple
#       font_size: small

# - name: disk
#   height: 26
#   panels:
#     - type: fact
#       # justify: center
#       source: disk
#       label: "default"
#       color: green
#       font_size: small

# - name: temp
#   height: 27
#   panels:
#     - type: fact
#       # justify: center
#       source: temp
#       label: "default"
#       color: orange
#       font_size: small

  - name: divider-3
    height: 5
    panels:
      - type: divider
        height: 1
        color: darkgrey

  - name: uptime
    height: 26
    panels:
      - type: fact
        justify: left
        source: uptime
        label: "default"
        color: grey
        font_size: small

  - name: config
    height: 26
    panels:
      - type: fact
        justify: right
        source: config_file
        label: "config: "
        color: pink
        font_size: small

  - name: debug
    height: 52
    background: chocolate
    panels:
      - type: debug
        color: tan
