---
# landscape-demo.yaml  --  clockish config
# ---------------------------------------------------------------------------
# Display layout configuration for clockish
# Display settings are in display.yaml  --  use configs/display/ili9486-landscape.yaml.
# ---------------------------------------------------------------------------

orientation: landscape

rows:
  - name: utc-clock
    height: 22.50%
    panels:
      - type: clock
        justify: left
        timezone: UTC
        label: " UTC"
        time_format: 24hs
        color: lime
        font_size: auto

  - name: divider-1
    height: "5px"
    panels:
      - type: divider
        height: "1px"
        color: darkgrey

  - name: utc-date
    height: 13.13%
    panels:
      - type: date
        justify: center
        timezone: UTC
        date_format: "%A, %B %-d  UTC"
        color: darklime
        font_size: auto

  - name: divider-2
    height: "5px"
    panels:
      - type: divider
        height: "1px"
        color: darkgrey


  - name: world-clocks
    height: 16.25%
    panels:
      - type: clock
        # justify: center
        timezone: America/Denver
        time_format: 24h
        color: cornflower
        font_size: auto
      - type: divider
        width: 2%
        color: black
      - type: clock
        # justify: center
        width: 35%
        background: darkred
        timezone: US/Eastern
        time_format: 24h
        color: orange
        font_size: auto
      - type: divider
        width: 2%
        color: black
      - type: clock
        # justify: center
        timezone: Asia/Kolkata
        time_format: 24h
        background: black
        color: brown
        font_size: auto

  - name: world-labels
    height: 13.13%
    panels:
      - type: text
        # justify: center
        label: " Denver"
        color: cornflower
        font_size: auto
        background: black
      - type: divider
        width: 2%
        color: black
      - type: text
        # justify: center
        width: 35%
        label: "US/Eastern"
        background: darkred
        color: orange
        font_size: auto
      - type: divider
        width: 2%
        color: black
      - type: text
        # justify: center
        label: "  India"
        font_size: auto
        color: brown

  - name: divider-3
    height: "5px"
    panels:
      - type: divider
        height: "1px"

  - name: wifi-info
    height: 10.63%
    panels:
      - type: wifi_graphic
        width: 9.17%
        # justify: center
        color: white
      - type: fact
        # justify: center
        width: 18%
        source: wifi_status
        color: ff8888
        font_size: auto
      - type: fact
        # justify: center
        width: 20%
        source: wifi_ssid
        label: "SSID "
        color: brightblue
        font_size: auto
      - type: fact
        # justify: center
        width: 35%
        source: wifi_signal
        label: " signal: "
        color: pink
        font_size: auto
      - type: fact
        # justify: center
        width: 18%
        source: wifi_quality
        label: "qual:"
        color: purple
        font_size: auto

  - name: host-ip
    height: 14.38%
    panels:
      - type: fact
        justify: left
        source: hostname
        color: green
        font_size: auto
      - type: fact
        justify: center
        source: ip
        color: green
        font_size: auto
      - type: debug
        color: silver
