---
# landscape-demo.yaml  --  clockish config
# ---------------------------------------------------------------------------
# Display layout configuration for clockish
# Display settings are in display.yaml  --  use configs/display/ili9486-landscape.yaml.
# ---------------------------------------------------------------------------

orientation: landscape
preview_size: "480x320"

rows:
#  - name: utc-clock
#    height: 33%
#    panels:
#      - type: clock
#        justify: center
#        timezone: UTC
#        time_format: 24hs
#        color: lime
#        font_size: auto
#        font_behavior: scale_numeric
  - name: clock
    height: 30%
    panels:
      - type: clock
        width: 66.67%
        justify: right
        timezone: US/Mountain
        time_format: "  %H:%M"
        color: silver   # classic warm nixie yellow-orange
        font_size: auto
        font_behavior: scale
#      - type: text
#        width: 3%
#        justify: center
#        label: ":"
#        color: grey
#        font_size: auto
#      - type: clock
#        width: 34%
#        justify: center
#        timezone: US/Mountain
#        time_format: "%M"
#        color: silver
#        font_size: auto
#        font_behavior: scale
      - type: clock
        width: 33%
        justify: left
        timezone: US/Mountain
        time_format: ":%S"
        color: grey
        font_size: auto
        #font_behavior: auto
  - name: divider-1
    height: 2%
    panels:
      - type: divider
        height: 1px
        color: darkgrey

  - name: utc-date
    height: 13%
    panels:
      - type: date
        justify: center
        timezone: UTC
        date_format: "%A, %B %-d  UTC"
        color: darklime
        font_size: auto

  - name: divider-2
    height: 2%
    panels:
      - type: divider
        height: 1px
        color: darkgrey


  - name: world-clocks
    height: 16%
    panels:
      - type: clock
        width: 32%
        # justify: center
        timezone: America/Denver
        time_format: 24h
        color: cornflower
        font_size: auto
      - type: divider
        width: 2%
        color: black
      - type: clock
        # justify: center
        width: 31%
        background: dimred
        timezone: US/Eastern
        time_format: 24h
        color: orange
        font_size: auto
      - type: divider
        width: 2%
        color: black
      - type: clock
        width: 32%
        # justify: center
        timezone: Asia/Kolkata
        time_format: 24h
        background: black
        color: brown
        font_size: auto

  - name: world-labels
    height: 13%
    panels:
      - type: text
        width: 32%
        # justify: center
        label: " Denver"
        color: cornflower
        font_size: auto
        background: black
      - type: divider
        width: 2%
        color: black
      - type: text
        # justify: center
        width: 31%
        label: "Atlanta"
        background: dimred
        color: orange
        font_size: small
      - type: divider
        width: 2%
        color: black
      - type: text
        width: 32%
        # justify: center
        label: "India"
        font_size: auto
        color: brown

  - name: world-temps
    height: 13%
    panels:
      - type: url-fact
        width: 32%
        url: |-
          https://api.open-meteo.com/v1/forecast?
          latitude=39.5727&longitude=-104.8494&current=temperature_2m&temperature_unit=fahrenheit
        json_path: "current.temperature_2m"
        interval: 20m
        justify: center
        color: cornflower
        fallback: "68°F"
        background: black
        font_size: small
        transform:
          - round: 0
          - suffix: "°F"

      - type: divider
        width: 2%
        color: black

      - type: url-fact
        width: 31%
        url: |-
          https://api.open-meteo.com/v1/forecast?
          latitude=33.8761&longitude=-84.4598&current=temperature_2m&temperature_unit=fahrenheit
        json_path: "current.temperature_2m"
        interval: 20m
        justify: center
        color: orange
        background: dimred
        font_size: small
        transform:
          - round: 0
          - suffix: "°F"
      - type: divider
        width: 2%
        color: black
      - type: url-fact
        width: 16%
        url: |-
          https://api.open-meteo.com/v1/forecast?
          latitude=12.680916&longitude=79.350600&current=temperature_2m&temperature_unit=fahrenheit
        json_path: "current.temperature_2m"
        interval: 20m
        justify: center
        color: brown
        background: black
        font_size: small
        transform:
          - round: 0
          - suffix: "°F"

      - type: url-fact
        width: 16%
        url: |-
          https://api.open-meteo.com/v1/forecast?
          latitude=12.680916&longitude=79.350600&current=temperature_2m&temperature_unit=celsius
        json_path: "current.temperature_2m"
        interval: 20m
        justify: center
        color: brown
        background: black
        font_size: small
        transform:
          - round: 0
          - suffix: "°C"

  - name: divider-3
    height: 2%
    panels:
      - type: divider
        height: 1px

  - name: wifi-info
    height: 10%
    panels:
      - type: wifi_graphic
        width: 10%
        color: darklime
      - type: blank
        width: 2%
      - type: fact
        width: 21%
        justify: center
        source: wifi_status
        color: grey
        font_size: auto
      - type: fact
        justify: center
        source: wifi_signal
        color: grey
        font_size: auto
      - type: fact
        source: ip
        justify: right
        color: grey
        font_size: auto
#
#  - name: debug
#    height: 5%
#    panels:
#      - type: fact
#        width: 40%
#        justify: center
#        source: ip
#        color: green
#        font_size: auto
#      - type: debug
